// Fetch a scraped map's JSON, preferring a pre-compressed `.gz` sibling and decompressing it
// in the browser. The app is a static export (no server), so a plain host may ship a 30 MB
// map uncompressed; a committed `<file>.gz` is ~1/7 the size and `DecompressionStream` inflates
// it here — cutting the download regardless of host config. Falls back to the plain JSON when
// there is no `.gz` or the browser lacks `DecompressionStream`. Pure `fetch` + streams, so it
// runs unchanged on the main thread or inside a Web Worker.
//
// `onProgress` receives the download fraction 0→1 (against the response's `content-length`),
// so a big map (SF, Columbus) can drive a real progress bar. It counts the bytes actually
// pulled over the wire — the compressed bytes for the `.gz` path — which is what the user
// waits on. Omitted or an absent length simply means no ticks (the caller shows it indeterminate).
export async function fetchMapText(url: string, onProgress?: (fraction: number) => void): Promise<string> {
  if (typeof DecompressionStream !== "undefined") {
    try {
      const gz = await fetch(`${url}.gz`);
      if (gz.ok && gz.body) {
        const counted = withProgress(gz.body, Number(gz.headers.get("content-length")) || 0, onProgress);
        const inflated = counted.pipeThrough(new DecompressionStream("gzip"));
        return await new Response(inflated).text();
      }
    } catch {
      // fall through to the uncompressed map
    }
  }
  const res = await fetch(url);
  if (!res.ok) throw new Error(`map fetch failed (${res.status}) for ${url}`);
  if (res.body) {
    const counted = withProgress(res.body, Number(res.headers.get("content-length")) || 0, onProgress);
    return await new Response(counted).text();
  }
  return await res.text();
}

// A scraped map's header: its GPS bounding box (`[lat_min, lon_min, lat_max,
// lon_max]`) and projection origin (`[lat, lon]`) — enough to place one map's
// extent inside another's local frame.
export type MapMeta = { place: string; bbox: [number, number, number, number]; origin: [number, number] };

// Fetch only a map's `meta` header: stream (and inflate, for the `.gz` sibling)
// just the first chunks until the meta object closes, then cancel the download.
// A county map is 30+ MB but its meta is the first ~200 bytes, so this costs one
// small read per map — cheap enough to probe every candidate at boot.
export async function fetchMapMeta(url: string): Promise<MapMeta | null> {
  const read = async (body: ReadableStream<Uint8Array>): Promise<MapMeta | null> => {
    const reader = body.getReader();
    const decoder = new TextDecoder();
    let text = "";
    try {
      while (text.length < 64 * 1024) {
        const { done, value } = await reader.read();
        if (value) text += decoder.decode(value, { stream: true });
        const m = /"meta"\s*:\s*(\{[^{}]*\})/.exec(text);
        if (m) {
          const meta = JSON.parse(m[1]) as Partial<MapMeta>;
          if (Array.isArray(meta.bbox) && meta.bbox.length === 4 && Array.isArray(meta.origin)) {
            return { place: meta.place ?? "", bbox: meta.bbox, origin: meta.origin as [number, number] };
          }
          return null;
        }
        if (done) return null;
      }
      return null;
    } finally {
      reader.cancel().catch(() => {});
    }
  };
  try {
    if (typeof DecompressionStream !== "undefined") {
      const gz = await fetch(`${url}.gz`);
      if (gz.ok && gz.body) {
        return await read(gz.body.pipeThrough(new DecompressionStream("gzip")));
      }
    }
    const res = await fetch(url);
    if (res.ok && res.body) return await read(res.body);
  } catch {
    // no meta — the caller simply skips this map's overlay
  }
  return null;
}

// A county map's silhouette sidecar (`<base>.outline.json`, generated by
// scripts/build-outlines.mjs from the map's own road network): a simplified
// polygon in the map's local frame, plus the projection origin to re-frame it.
export type CountyOutline = { origin: [number, number]; points: [number, number][] };

export async function fetchCountyOutline(url: string): Promise<CountyOutline | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const o = (await res.json()) as Partial<CountyOutline>;
    if (!Array.isArray(o.origin) || !Array.isArray(o.points) || o.points.length < 3) return null;
    return { origin: o.origin as [number, number], points: o.points as [number, number][] };
  } catch {
    return null; // no sidecar — the overlay falls back to the bbox rectangle
  }
}

// Tee a byte stream through a pass-through that reports cumulative bytes / total as a 0→1
// fraction. No total (unknown length) → no ticks, and the stream is returned untouched.
function withProgress<T extends Uint8Array>(
  body: ReadableStream<T>,
  total: number,
  onProgress?: (fraction: number) => void,
): ReadableStream<T> {
  if (!onProgress || total <= 0) return body;
  let received = 0;
  return body.pipeThrough(
    new TransformStream<T, T>({
      transform(chunk, controller) {
        received += chunk.byteLength;
        onProgress(Math.min(1, received / total));
        controller.enqueue(chunk);
      },
    }),
  );
}
